/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsul.lpoo.clinica.gui.consulta;

import br.edu.ifsul.lpoo.clinica.Controle;
import br.edu.ifsul.lpoo.clinica.model.Consulta;
import br.edu.ifsul.lpoo.clinica.model.Medico;
import br.edu.ifsul.lpoo.clinica.model.Pet;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class JPanelConsultaFormulario extends javax.swing.JPanel {

    private JPanelConsulta pnlConsulta;
    private Controle controle;
    
    private Consulta consulta;
    private SimpleDateFormat format;
    
    public JPanelConsultaFormulario(JPanelConsulta pnlConsulta, Controle controle) {
        this.pnlConsulta = pnlConsulta;
        this.controle = controle;
        initComponents();
        format = new SimpleDateFormat("dd/MM/yyyy");
    }
    
    public void populaComboPet(){
        
        cbxPet.removeAllItems();//zera o combo

        DefaultComboBoxModel model =  (DefaultComboBoxModel) cbxPet.getModel();

        model.addElement("Selecione"); //primeiro item        
        try {

            List<Pet> listPet = controle.getConexaoJDBC().listPet();
            for(Pet p : listPet){
                model.addElement(p);
            }

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this, "Erro ao listar pet -:"+ex.getLocalizedMessage(), "Pets", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }  
        
        
    }
    
    public Consulta getConsulta(){
        
        //validacao do formulario
         if(txfObservacao.getText().trim().length() > 0
                && txfValor.getText().trim().length() > 0
                && txfMedico.getText().trim().length() > 0
                && cbxPet.getSelectedIndex() > 0){

            Consulta c = new Consulta();
            if (txfId.getText().trim().length() > 0) {
                c.setId(Integer.parseInt(txfId.getText().trim()));
            }
            c.setObservacao(txfObservacao.getText().trim());            
            c.setValor(Float.parseFloat(txfValor.getText().trim()));
            Medico m = new Medico();
            m.setCpf(txfMedico.getText().trim());
            c.setMedico(m);
            c.setPet((Pet) cbxPet.getSelectedItem());

            return c;
         }

         return null;
    }
    
    public void setConsulta(Consulta c){

        if(c == null){//se o parametro estiver nullo, limpa o formulario
            txfId.setText("");
            txfId.setEditable(false);
            txfObservacao.setText("");
            txfValor.setText("");
            txfMedico.setText("");
            cbxPet.setSelectedIndex(0);
            consulta = null;

        }else{
            consulta = c;
            txfId.setText(consulta.getId().toString());
            txfId.setEditable(false);
            txfObservacao.setText(consulta.getObservacao());
            txfValor.setText(consulta.getValor().toString());
            txfMedico.setText(consulta.getMedico().getCpf());
            cbxPet.getModel().setSelectedItem(consulta.getPet());          

        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlSul = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlCentro = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        txfId = new javax.swing.JTextField();
        lblObservacao = new javax.swing.JLabel();
        txfObservacao = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        txfValor = new javax.swing.JTextField();
        lblMedico = new javax.swing.JLabel();
        txfMedico = new javax.swing.JTextField();
        lblPet = new javax.swing.JLabel();
        cbxPet = new javax.swing.JComboBox<>();

        setLayout(new java.awt.BorderLayout());

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        pnlSul.add(btnSalvar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlSul.add(btnCancelar);

        add(pnlSul, java.awt.BorderLayout.PAGE_END);

        pnlCentro.setLayout(new java.awt.GridBagLayout());

        lblId.setText("Id:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlCentro.add(lblId, gridBagConstraints);

        txfId.setColumns(2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlCentro.add(txfId, gridBagConstraints);

        lblObservacao.setText("Observação:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlCentro.add(lblObservacao, gridBagConstraints);

        txfObservacao.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlCentro.add(txfObservacao, gridBagConstraints);

        lblValor.setText("Valor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlCentro.add(lblValor, gridBagConstraints);

        txfValor.setColumns(4);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlCentro.add(txfValor, gridBagConstraints);

        lblMedico.setText("CPF do Medico:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlCentro.add(lblMedico, gridBagConstraints);

        txfMedico.setColumns(11);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlCentro.add(txfMedico, gridBagConstraints);

        lblPet.setText("Pet:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlCentro.add(lblPet, gridBagConstraints);

        cbxPet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlCentro.add(cbxPet, gridBagConstraints);

        add(pnlCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        Consulta c = getConsulta();//recupera os dados do formulÃ¡rio

        if(c != null){

            try {

                pnlConsulta.getControle().getConexaoJDBC().persist(c);

                JOptionPane.showMessageDialog(this, "Consulta armazenada!", "Salvar", JOptionPane.INFORMATION_MESSAGE);

                pnlConsulta.showTela("tela_consulta_listagem");

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao salvar consulta! : "+ex.getMessage(), "Salvar", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }

        }else{

            JOptionPane.showMessageDialog(this, "Preencha o formulário!", "Edição", JOptionPane.INFORMATION_MESSAGE);
        }
        
        pnlConsulta.showTela("tela_consulta_listagem");
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        pnlConsulta.showTela("tela_consulta_listagem");
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbxPet;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMedico;
    private javax.swing.JLabel lblObservacao;
    private javax.swing.JLabel lblPet;
    private javax.swing.JLabel lblValor;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlSul;
    private javax.swing.JTextField txfId;
    private javax.swing.JTextField txfMedico;
    private javax.swing.JTextField txfObservacao;
    private javax.swing.JTextField txfValor;
    // End of variables declaration//GEN-END:variables
}
