/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsul.lpoo.clinica.gui.consulta;

import br.edu.ifsul.lpoo.clinica.Controle;
import br.edu.ifsul.lpoo.clinica.model.Consulta;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class JPanelConsultaListagem extends javax.swing.JPanel {

    private JPanelConsulta pnlConsulta;
    private Controle controle;
    private SimpleDateFormat format;
    
    public JPanelConsultaListagem(JPanelConsulta pnlConsulta, Controle controle) {
        this.pnlConsulta = pnlConsulta;
        this.controle = controle;
        initComponents();
        format = new SimpleDateFormat("dd/MM/yyyy");
    }
    
    public void populaTable(){
        
        DefaultTableModel model =  (DefaultTableModel) tblListagem.getModel();//recuperacao do modelo da tabela

        model.setRowCount(0);//elimina as linhas existentes (reset na tabela)

        try {

            List<Consulta> listConsulta = controle.getConexaoJDBC().listConsulta();
            for(Consulta c : listConsulta){
                                
                model.addRow(new Object[]{c, c.getPet().getNome(), c.getMedico().getNome(),
                    format.format(c.getData().getTime()) ,format.format(c.getData_retorno().getTime()), 
                    c.getValor(), c.getId()});
            }

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this, "Erro ao listar consultas -:"+ex.getLocalizedMessage(), "Consultas", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSul = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        pnlCentro = new javax.swing.JPanel();
        scpRolagem = new javax.swing.JScrollPane();
        tblListagem = new javax.swing.JTable();
        pnlNorte = new javax.swing.JPanel();
        lblFiltrarObs = new javax.swing.JLabel();
        txfFiltrarObs = new javax.swing.JTextField();
        btnFiltrar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        pnlSul.add(btnNovo);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        pnlSul.add(btnEditar);

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        pnlSul.add(btnRemover);

        add(pnlSul, java.awt.BorderLayout.PAGE_END);

        pnlCentro.setLayout(new java.awt.BorderLayout());

        tblListagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Observação", "Pet", "Medico", "Data", "Data de Retorno", "Valor", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scpRolagem.setViewportView(tblListagem);

        pnlCentro.add(scpRolagem, java.awt.BorderLayout.CENTER);

        add(pnlCentro, java.awt.BorderLayout.CENTER);

        lblFiltrarObs.setText("Filtrar por observação:");
        pnlNorte.add(lblFiltrarObs);

        txfFiltrarObs.setColumns(20);
        pnlNorte.add(txfFiltrarObs);

        btnFiltrar.setText("Filtrar");
        pnlNorte.add(btnFiltrar);

        add(pnlNorte, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        pnlConsulta.showTela("tela_consulta_formulario");
        pnlConsulta.getFormulario().setConsulta(null);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int indice = tblListagem.getSelectedRow();//recupera a linha selecionada
        if (indice > -1) {

            DefaultTableModel model = (DefaultTableModel) tblListagem.getModel(); //recuperacao do modelo da table

            Vector linha = (Vector) model.getDataVector().get(indice);//recupera o vetor de dados da linha selecionada

            Consulta c = (Consulta) linha.get(0);

            pnlConsulta.showTela("tela_consulta_formulario");
            pnlConsulta.getFormulario().setConsulta(c);

        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma linha para editar!", "Edição", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        int indice = tblListagem.getSelectedRow();//recupera a linha selecionada
        if (indice > -1) {

            DefaultTableModel model = (DefaultTableModel) tblListagem.getModel(); //recuperacao do modelo da table

            Vector linha = (Vector) model.getDataVector().get(indice);//recupera o vetor de dados da linha selecionada

            Consulta c = (Consulta) linha.get(0);
            
            try {
                    pnlConsulta.getControle().getConexaoJDBC().remover(c);
                    JOptionPane.showMessageDialog(this, "Consulta removida!", "Consulta", JOptionPane.INFORMATION_MESSAGE);
                    populaTable(); //refresh na tabela

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao remover consulta -:"+ex.getLocalizedMessage(), "Consulta", JOptionPane.ERROR_MESSAGE);
                    ex.printStackTrace();
                }     

        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma linha para remover!", "Remoção", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnRemoverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRemover;
    private javax.swing.JLabel lblFiltrarObs;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlNorte;
    private javax.swing.JPanel pnlSul;
    private javax.swing.JScrollPane scpRolagem;
    private javax.swing.JTable tblListagem;
    private javax.swing.JTextField txfFiltrarObs;
    // End of variables declaration//GEN-END:variables
}
